SETS = [
  "10th Edition",
  "2010 Core Set",
  "2011 Core Set",
  "2012 Core Set",
  "2013 Core Set",
  "2014 Core Set",
  "2015 Core Set",
  "3rd Edition",
  "4th Edition",
  "5th Edition",
  "6th Edition",
  "7th Edition",
  "8th Edition",
  "9th Edition",
  "Aether Revolt",
  "Alara Reborn",
  "Alliances",
  "Alpha",
  "Amonkhet",
  "Anthologies",
  "Antiquities",
  "Apocalypse",
  "Arabian Nights",
  "Archenemy",
  "Archenemy - Nicol Bolas",
  "Art Series",
  "Avacyn Restored",
  "Battle Royale",
  "Battle for Zendikar",
  "Battlebond",
  "Beatdown",
  "Beta",
  "Betrayers of Kamigawa",
  "Born of the Gods",
  "Champions of Kamigawa",
  "Chronicles",
  "Coldsnap",
  "Coldsnap Theme Decks",
  "Collectors Ed",
  "Collectors Ed Intl",
  "Commander",
  "Commander 2013",
  "Commander 2014",
  "Commander 2015",
  "Commander 2016",
  "Commander 2017",
  "Commander 2018",
  "Commander 2019",
  "Commander Anthology",
  "Commander Anthology Vol. II",
  "Commander's Arsenal",
  "Conflux",
  "Conspiracy",
  "Conspiracy - Take the Crown",
  "Core Set 2019",
  "Core Set 2020",
  "Dark Ascension",
  "Darksteel",
  "Deckmaster",
  "Dissension",
  "Dominaria",
  "Dragon's Maze",
  "Dragons of Tarkir",
  "Duel Decks: Ajani Vs. Nicol Bolas",
  "Duel Decks: Anthology",
  "Duel Decks: Blessed Vs. Cursed",
  "Duel Decks: Divine Vs. Demonic",
  "Duel Decks: Elspeth Vs. Kiora",
  "Duel Decks: Elspeth Vs. Tezzeret",
  "Duel Decks: Elves Vs. Goblins",
  "Duel Decks: Elves Vs. Inventors",
  "Duel Decks: Garruk Vs. Liliana",
  "Duel Decks: Heroes Vs. Monsters",
  "Duel Decks: Izzet Vs. Golgari",
  "Duel Decks: Jace Vs. Chandra",
  "Duel Decks: Jace Vs. Vraska",
  "Duel Decks: Knights Vs. Dragons",
  "Duel Decks: Merfolk Vs. Goblins",
  "Duel Decks: Mind Vs. Might",
  "Duel Decks: Nissa Vs. Ob Nixilis",
  "Duel Decks: Phyrexia Vs. The Coalition",
  "Duel Decks: Sorin Vs. Tibalt",
  "Duel Decks: Speed Vs. Cunning",
  "Duel Decks: Venser Vs. Koth",
  "Duel Decks: Zendikar Vs. Eldrazi",
  "Duels of the Planeswalkers",
  "Eldritch Moon",
  "Eternal Masters",
  "Eventide",
  "Exodus",
  "Explorers of Ixalan",
  "Fallen Empires",
  "Fate Reforged",
  "Fifth Dawn",
  "From the Vault: Angels",
  "From the Vault: Annihilation",
  "From the Vault: Dragons",
  "From the Vault: Exiled",
  "From the Vault: Legends",
  "From the Vault: Lore",
  "From the Vault: Realms",
  "From the Vault: Relics",
  "From the Vault: Transform",
  "From the Vault: Twenty",
  "Future Sight",
  "Game Night",
  "Game Night 2019",
  "Gatecrash",
  "Global Series: Jiang Yanggu & Mu Yanling",
  "Guildpact",
  "Guilds of Ravnica",
  "Guilds of Ravnica: Guild Kits",
  "Homelands",
  "Hour of Devastation",
  "Ice Age",
  "Iconic Masters",
  "Innistrad",
  "Invasion",
  "Ixalan",
  "Journey into Nyx",
  "Judgment",
  "Kaladesh",
  "Khans of Tarkir",
  "Legends",
  "Legions",
  "Lorwyn",
  "Magic Origins",
  "Masterpiece Series: Expeditions",
  "Masterpiece Series: Inventions",
  "Masterpiece Series: Invocations",
  "Masterpiece Series: Mythic Edition",
  "Masters 25",
  "Mercadian Masques",
  "Mirage",
  "Mirrodin",
  "Mirrodin Besieged",
  "Modern Event Deck",
  "Modern Horizons",
  "Modern Masters",
  "Modern Masters 2015",
  "Modern Masters 2017",
  "Morningtide",
  "Mystery Booster",
  "Nemesis",
  "New Phyrexia",
  "Oath of the Gatewatch",
  "Odyssey",
  "Onslaught",
  "Planar Chaos",
  "Planechase",
  "Planechase 2012",
  "Planechase Anthology",
  "Planeshift",
  "Portal",
  "Portal 3K",
  "Portal II",
  "Premium Deck Series: Fire & Lightning",
  "Premium Deck Series: Graveborn",
  "Premium Deck Series: Slivers",
  "Promo Pack",
  "Promotional",
  "Prophecy",
  "Ravnica",
  "Ravnica Allegiance",
  "Ravnica Allegiance: Guild Kits",
  "Return to Ravnica",
  "Rise of the Eldrazi",
  "Rivals of Ixalan",
  "Saviors of Kamigawa",
  "Scars of Mirrodin",
  "Scourge",
  "Secret Lair",
  "Shadowmoor",
  "Shadows Over Innistrad",
  "Shards of Alara",
  "Signature Spellbook: Gideon",
  "Signature Spellbook: Jace",
  "Starter 1999",
  "Starter 2000",
  "Stronghold",
  "Tempest",
  "The Dark",
  "Theros",
  "Throne of Eldraine",
  "Throne of Eldraine Variants",
  "Time Spiral",
  "Timeshifted",
  "Torment",
  "Ultimate Box Topper",
  "Ultimate Masters",
  "Unglued",
  "Unhinged",
  "Unlimited",
  "Unstable",
  "Urza's Destiny",
  "Urza's Legacy",
  "Urza's Saga",
  "Vanguard",
  "Visions",
  "War of the Spark",
  "War of the Spark JPN Planeswalkers",
  "Weatherlight",
  "World Championships",
  "Worldwake",
  "Zendikar",
]
